#!/bin/bash

DATABASE_USER="$1"
DATABASE_PASSWORD="$2"
DATABASE_NAME="$3"
DATABASE_HOST="$4"

# Create a new MySQL database
mysql -u"$DATABASE_USER" -p"$DATABASE_PASSWORD" -h"$DATABASE_HOST" -e "CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;"

echo "Database created"